#!/bin/bash
# services/europa-node/scripts/bootstrap.sh
#
# One-shot operator bootstrap. Generates everything you need to spin
# up a new Europa Node:
#
#   - Operator Nostr nsec (long-lived; signs your listing)
#   - WireGuard server keypair (long-lived; in /etc/wireguard/)
#   - Cashu P2PK keypair (long-lived; for Cashu-locked tokens)
#   - A starting config.toml seeded with all of the above
#
# Idempotent in the sense that it refuses to overwrite an existing
# secret. If you re-run it after a partial failure, delete the file
# the script complains about and try again.
#
# Requires: wg, openssl, awk, sed. On Debian/Ubuntu:
#   sudo apt install wireguard-tools openssl
#
# Usage:
#   ./scripts/bootstrap.sh           # interactive — prompts for hostname etc.
#   PUBLIC_HOST=vpn.example.com \
#   COUNTRY=US REGION=US-East GEOHASH=dr5regw \
#     ./scripts/bootstrap.sh         # non-interactive
set -euo pipefail

# ── Paths ───────────────────────────────────────────────────────────
HERE="$(cd "$(dirname "$0")/.." && pwd)"
TARGET_DIR="${TARGET_DIR:-$HERE}"
CONFIG_DIR="$TARGET_DIR/config"
SECRETS_DIR="$TARGET_DIR/secrets"
DATA_DIR="$TARGET_DIR/data"

mkdir -p "$CONFIG_DIR" "$SECRETS_DIR" "$DATA_DIR"
chmod 700 "$SECRETS_DIR"

# ── Required tools ─────────────────────────────────────────────────
for cmd in wg openssl awk sed; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "Error: $cmd not installed." >&2; exit 1; }
done

# ── Inputs (env-or-prompt) ──────────────────────────────────────────
prompt() {
  local var="$1" default="$2" desc="$3"
  if [ -z "${!var:-}" ]; then
    read -rp "$desc [$default]: " val
    printf -v "$var" "%s" "${val:-$default}"
  fi
}

prompt PUBLIC_HOST  "vpn.example.com"      "Public hostname clients will dial"
prompt D_TAG        "vpn-$(date +%Y)"      "NIP-99 listing identifier (d-tag)"
prompt TITLE        "My Europa Node"       "Listing title shown to clients"
prompt COUNTRY      "US"                   "ISO country code"
prompt REGION       ""                     "Sub-region (e.g. US-East). Blank = omit"
prompt GEOHASH      ""                     "Geohash for the map view (blank = omit)"

# ── Generate nsec ──────────────────────────────────────────────────
NSEC_FILE="$SECRETS_DIR/nsec"
if [ -f "$NSEC_FILE" ]; then
  echo "✓ nsec already at $NSEC_FILE — leaving it alone."
else
  # 32 random bytes hex; signing libs accept this directly.
  openssl rand -hex 32 > "$NSEC_FILE"
  chmod 600 "$NSEC_FILE"
  echo "✓ wrote nsec to $NSEC_FILE (mode 600)"
fi

# ── Generate WireGuard server keypair ──────────────────────────────
WG_KEY="$SECRETS_DIR/wg-server.key"
WG_PUB="$SECRETS_DIR/wg-server.pub"
if [ -f "$WG_KEY" ]; then
  echo "✓ WireGuard server key already at $WG_KEY"
else
  umask 077
  wg genkey | tee "$WG_KEY" | wg pubkey > "$WG_PUB"
  chmod 600 "$WG_KEY"
  chmod 644 "$WG_PUB"
  echo "✓ generated WireGuard server keypair"
fi
WG_SERVER_PUBKEY="$(cat "$WG_PUB")"

# ── Generate Cashu P2PK keypair ────────────────────────────────────
# secp256k1 private key + compressed-form public key with 02/03 prefix.
P2PK_PRIV="$SECRETS_DIR/cashu-p2pk.key"
P2PK_PUB_FILE="$SECRETS_DIR/cashu-p2pk.pub"
if [ -f "$P2PK_PRIV" ]; then
  echo "✓ Cashu P2PK key already at $P2PK_PRIV"
else
  # Generate ephemeral EC keypair, extract raw bytes.
  openssl ecparam -name secp256k1 -genkey -noout 2>/dev/null \
    | openssl ec -outform DER 2>/dev/null \
    | head -c 64 | tail -c 32 \
    | xxd -p -c 32 > "$P2PK_PRIV"
  chmod 600 "$P2PK_PRIV"
  # The simple way to derive the compressed pubkey from a hex privkey
  # is via a small openssl wrapper or a node one-liner; we prompt
  # the operator to derive it once with a tool of their choice.
  echo "✓ generated Cashu P2PK private key (hex) at $P2PK_PRIV"
  echo "  Derive the compressed-form public key once with:"
  echo "    npm exec -y --package=@noble/secp256k1 -- node -e \\"
  echo "      \"const s = require('@noble/secp256k1'); const k = require('fs').readFileSync('$P2PK_PRIV','utf8').trim(); console.log('02' + Buffer.from(s.getPublicKey(k, true)).slice(1).toString('hex'));\""
  echo "  and write the resulting line to $P2PK_PUB_FILE."
fi
P2PK_PUB="$(cat "$P2PK_PUB_FILE" 2>/dev/null || echo "REPLACE_WITH_P2PK_PUBKEY")"

# ── Write config.toml ──────────────────────────────────────────────
CONFIG_FILE="$CONFIG_DIR/config.toml"
if [ -f "$CONFIG_FILE" ]; then
  echo "ℹ $CONFIG_FILE already exists — not overwriting."
  echo "  Re-run with TARGET_DIR pointing somewhere else, or delete and retry."
else
  REGION_BLOCK="[listing.region]
country = \"$COUNTRY\""
  [ -n "$REGION" ] && REGION_BLOCK+="
sub = \"$REGION\""
  [ -n "$GEOHASH" ] && REGION_BLOCK+="
geohash = \"$GEOHASH\""

  cat > "$CONFIG_FILE" <<EOF
# Generated by bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Edit freely; see ../config.example.toml for the field reference.

[server]
host = "0.0.0.0"
port = 8080
public_host = "$PUBLIC_HOST"

[db]
path = "/var/lib/europa-node/sessions.db"

[wireguard]
interface = "wg0"
endpoint_host = "$PUBLIC_HOST"
endpoint_port = 51820
server_pubkey = "$WG_SERVER_PUBKEY"
subnet_cidr = "10.42.0.0/24"
dns = ["1.1.1.1", "9.9.9.9"]

[lightning]
# Flip enabled = true after you've got a phoenixd / LND backend wired up.
enabled = false
backend = "stub"
# base_url = "http://localhost:9740"
# api_token = ""

[cashu]
# Flip enabled = true after you've set a mint URL + your P2PK privkey.
enabled = false
# mint_url = "https://mint.example.com"
# p2pk_privkey_hex = "<read $P2PK_PRIV>"

[nostr]
relays = [
  "wss://relay.damus.io",
  "wss://nos.lol",
  "wss://relay.snort.social",
]
nsec_file = "/etc/europa-node/secret/nsec"

[listing]
d_tag = "$D_TAG"
title = "$TITLE"
protocols = ["wireguard"]
policies = ["no-logs"]
content = """
Independent Europa Node. WireGuard.
"""

$REGION_BLOCK

[[listing.prices]]
amount = 100
currency = "sat"
unit = "hour"

[[listing.prices]]
amount = 1000
currency = "sat"
unit = "day"

[[listing.payment_methods]]
type = "lightning"
endpoint = "https://$PUBLIC_HOST/lnurlp"
mechanism = "lnurl-pay"

# Uncomment once you've enabled Cashu above:
# [[listing.payment_methods]]
# type = "cashu"
# mint = "https://mint.example.com"
# p2pk = "$P2PK_PUB"
# endpoint = "https://$PUBLIC_HOST/purchase"
EOF
  echo "✓ wrote config to $CONFIG_FILE"
fi

# ── Caddyfile substitution ─────────────────────────────────────────
CADDY_TEMPLATE="$TARGET_DIR/Caddyfile"
if [ -f "$CADDY_TEMPLATE" ] && grep -q "vpn.example.com" "$CADDY_TEMPLATE"; then
  sed -i.bak "s|vpn.example.com|$PUBLIC_HOST|g" "$CADDY_TEMPLATE"
  rm -f "$CADDY_TEMPLATE.bak"
  echo "✓ updated Caddyfile to reference $PUBLIC_HOST"
fi

echo
echo "Next steps:"
echo "  1. Configure your host's WireGuard interface (wg0) using"
echo "     $WG_KEY as PrivateKey. See docs/spec.md §2.1 for the wg-quick template."
echo "  2. Forward UDP 51820 to this host."
echo "  3. docker compose up -d  (if using the docker-compose path)"
echo "  4. Once it's up, browse europa.westernbtc.com to confirm your"
echo "     listing shows in the directory."
